name: Github Action for Thesis and Website Update
on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          working_directory: thesis
          root_file: main.tex
      - name: move
        run: mkdir -p github_deploy && mv thesis/main.pdf github_deploy/
      - name: Deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
      - name: Update Website Repository
        uses: actions/checkout@v3
        with:
          repository: lukefleed/website
          path: website
          token: ${{ secrets.PAT }}
      - name: Copy PDF to Website
        run: cp github_deploy/main.pdf website/public/thesis/main.pdf
      - name: Commit and Push Changes
        run: |
          cd website
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add public/thesis/main.pdf
          git commit -m "Update thesis PDF"
          git push
